environment:
  SLS_DEBUG: "*"

service: pitch-deck-viewer

provider:
  name: aws
  runtime: nodejs14.x

layers:
  nodeCanvas: 
    package:
      artifact: infrastructure/aws-lambda/nodeCanvasLib.zip

functions:
  pdfToImageArray:
    handler: infrastructure/aws-lambda/handlers.pdfToImageArrayHandler

    events:
      - http:
          path: pdf-to-image-array
          method: POST

    layers:
      - { Ref: NodeCanvasLambdaLayer }

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  include:
    - infrastructure/aws-lambda/handlers.ts
