environment:
  SLS_DEBUG: "*"

service: pitch-deck-viewer

provider:
  name: aws
  runtime: nodejs14.x
  memory: 16384

layers:
  nodeCanvas: 
    package:
      artifact: infrastructure/aws-lambda/nodeCanvasLib.zip

functions:
  uploadPitchDeck:
    handler: infrastructure/aws-lambda/handlers.uploadPitchDeckHandler

    events:
      - http:
          path: upload-pitchdeck
          method: POST

    layers:
      - { Ref: NodeCanvasLambdaLayer }

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  include:
    - infrastructure/aws-lambda/handlers.ts
